# Generated by Django 4.2.13 on 2024-06-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklistitem',
            old_name='checked',
            new_name='completed',
        ),
    ]
