# Generated by Django 4.2.13 on 2024-06-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_entry_last_updated_entry_owner_entry_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-time_created']},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='body',
        ),
    ]
