# Generated by Django 4.2.13 on 2024-07-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_alter_entry_body_alter_entry_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
