# Generated by Django 4.2.13 on 2024-07-08 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_rename_date_created_goalinstance_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='days',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='goalinstance',
            name='time_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
