# Generated by Django 4.2.13 on 2024-07-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_goal_days_alter_goalinstance_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='days',
            field=models.JSONField(default=dict),
        ),
    ]
