# Generated by Django 4.2.13 on 2024-07-16 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_alter_goal_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='time_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
