# Generated by Django 4.2.13 on 2024-07-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_goal_time_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoalInstance',
        ),
    ]
